# Generated by Django 5.2 on 2026-03-04 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0006_token_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='thumbnail',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='thumbnails/'),
        ),
    ]
